window.FW_DATA = {
  "host": { "name": "Inspector Marmalade", "emoji": "🐈" },
  "characters": [
    { "id": "socks",    "emoji": "🧦", "name": "Captain Socks",     "tagline": "Never met a sock I didn't lose.", "unlockAt": 0 },
    { "id": "thunder",  "emoji": "⚡", "name": "Grandma Thunder",   "tagline": "Back in my day we had TWO cupcakes.", "unlockAt": 0 },
    { "id": "wiggles",  "emoji": "🥸", "name": "Professor Wiggles", "tagline": "Scientifically speaking, it wasn't me.", "unlockAt": 0 },
    { "id": "bigfoot",  "emoji": "🦶", "name": "Baby Bigfoot",      "tagline": "Big feet, tiny crimes.", "unlockAt": 0 },
    { "id": "cat",      "emoji": "🐱", "name": "The Cat",           "tagline": "Meow. That's all you're getting.", "unlockAt": 0 },
    { "id": "sprinkles","emoji": "🧁", "name": "Sir Sprinkles",     "tagline": "A gentleman never eats and tells.", "unlockAt": 0 },
    { "id": "dino",     "emoji": "🦖", "name": "Dino Dan",          "tagline": "My arms are too short to do crimes.", "unlockAt": 0 },
    { "id": "beans",    "emoji": "🧙", "name": "Wizard Beans",      "tagline": "It was magic. Probably.", "unlockAt": 0 },
    { "id": "nana",     "emoji": "🥷", "name": "Ninja Nana",        "tagline": "You didn't see me. You never see me.", "unlockAt": 3 },
    { "id": "toaster",  "emoji": "🤖", "name": "Robo Toaster",      "tagline": "Beep boop. Not guilty. Beep.", "unlockAt": 6 },
    { "id": "pickle",   "emoji": "🦄", "name": "Princess Pickle",   "tagline": "Royalty does not do crimes. Usually.", "unlockAt": 10 },
    { "id": "snout",    "emoji": "🐷", "name": "Sergeant Snout",    "tagline": "I sniff out trouble. Then I eat it.", "unlockAt": 15 },
    { "id": "booboo",   "emoji": "👻", "name": "Boo Boo",           "tagline": "I can walk through walls, not fridges.", "unlockAt": 20 },
    { "id": "zack",     "emoji": "🧟", "name": "Zombie Zack",       "tagline": "Braaains. And also snacks.", "unlockAt": 25 },
    { "id": "ollie",    "emoji": "🐙", "name": "Ollie Eight Arms",  "tagline": "Eight arms, zero alibis.", "unlockAt": 30 },
    { "id": "obvious",  "emoji": "🦸", "name": "Captain Obvious",   "tagline": "The culprit is definitely someone.", "unlockAt": 40 }
  ],
  "places": [
    { "id": "kitchen",  "emoji": "🍳", "name": "the kitchen",     "short": "Kitchen",     "clues": ["There's a trail of flour leading from the kitchen.", "The fridge door was left wide open. Someone was in the kitchen."] },
    { "id": "bathroom", "emoji": "🛁", "name": "the bathroom",    "short": "Bathroom",    "clues": ["Wet footprints! The culprit came from the bathroom.", "A rubber duck was found at the scene. Someone came from the bathroom."] },
    { "id": "garage",   "emoji": "🔧", "name": "the garage",      "short": "Garage",      "clues": ["Fresh oil stains on the floor. The culprit was in the garage.", "A wrench was found at the scene. Someone had been in the garage."] },
    { "id": "bedroom",  "emoji": "🛏️", "name": "the bedroom",    "short": "Bedroom",     "clues": ["A pillow feather was found at the scene. The culprit came from the bedroom.", "The bedroom door was left wide open. Someone snuck out of there."] },
    { "id": "backyard", "emoji": "🌳", "name": "the backyard",    "short": "Backyard",    "clues": ["Grass stains on the carpet. The culprit came in from the backyard.", "Muddy footprints lead in from the backyard."] },
    { "id": "living",   "emoji": "🛋️", "name": "the living room","short": "Living Room", "clues": ["The couch cushions are still warm. The culprit was in the living room.", "The TV was left on. Someone was in the living room."] },
    { "id": "attic",    "emoji": "🕸️", "name": "the attic",      "short": "Attic",       "clues": ["Cobwebs at the scene! The culprit had been up in the attic.", "Dust everywhere. Someone came down from the attic."] },
    { "id": "car",      "emoji": "🚗", "name": "the car",         "short": "Car",         "clues": ["Car keys were found at the scene. The culprit had been in the car.", "The car seat was moved. Someone was hiding in the car."] }
  ],
  "colors": [
    { "id": "red",    "emoji": "🟥", "name": "red",    "short": "Red",    "css": "#e63946", "clues": ["A red thread was caught on the door handle.", "A witness saw a flash of red."] },
    { "id": "blue",   "emoji": "🟦", "name": "blue",   "short": "Blue",   "css": "#3a86ff", "clues": ["A blue button was found at the scene.", "The security teddy bear reports: the culprit wore blue."] },
    { "id": "green",  "emoji": "🟩", "name": "green",  "short": "Green",  "css": "#2dc653", "clues": ["A green sleeve was spotted disappearing around the corner.", "Green fuzz was found at the scene."] },
    { "id": "yellow", "emoji": "🟨", "name": "yellow", "short": "Yellow", "css": "#ffd60a", "clues": ["A yellow thread was found on the floor.", "The goldfish saw someone in yellow. The goldfish never lies."] },
    { "id": "purple", "emoji": "🟪", "name": "purple", "short": "Purple", "css": "#9d4edd", "clues": ["A purple sock was left behind.", "A witness saw a blur of purple."] },
    { "id": "orange", "emoji": "🟧", "name": "orange", "short": "Orange", "css": "#fb8500", "clues": ["Orange fluff was found at the scene.", "The dog barked at someone wearing orange."] }
  ],
  "snacks": [
    { "id": "cookie",   "emoji": "🍪", "name": "cookies",   "short": "Cookies",   "clues": ["Cookie crumbs were found at the scene.", "Chocolate chip fingerprints. The culprit had been eating cookies."] },
    { "id": "banana",   "emoji": "🍌", "name": "a banana",  "short": "Banana",    "clues": ["A banana peel was left at the scene.", "It smells like bananas in here. Suspicious."] },
    { "id": "pizza",    "emoji": "🍕", "name": "pizza",     "short": "Pizza",     "clues": ["A greasy pizza fingerprint was found on the wall.", "A slice of pepperoni was found at the scene."] },
    { "id": "pickle",   "emoji": "🥒", "name": "pickles",   "short": "Pickles",   "clues": ["Pickle juice was dripped all over the floor.", "The whole room smells like pickles."] },
    { "id": "icecream", "emoji": "🍦", "name": "ice cream", "short": "Ice Cream", "clues": ["A sticky ice cream puddle was found at the scene.", "A melty ice cream handprint was found on the door."] },
    { "id": "popcorn",  "emoji": "🍿", "name": "popcorn",   "short": "Popcorn",   "clues": ["Popcorn kernels were scattered at the scene.", "Buttery fingerprints everywhere. Popcorn."] },
    { "id": "cheese",   "emoji": "🧀", "name": "cheese",    "short": "Cheese",    "clues": ["A cheese wrapper was found at the scene.", "The culprit left behind a very strong smell of cheese."] },
    { "id": "grapes",   "emoji": "🍇", "name": "grapes",    "short": "Grapes",    "clues": ["A squished grape was found on the floor.", "Grape juice footprints lead away from the scene."] }
  ],
  "cases": [
    { "id": "cupcake",    "emoji": "🧁", "title": "The Case of the Last Cupcake",        "blurb": "There was ONE cupcake left, and it had your name on it. Now there's just a wrapper and a whole lot of crumbs." },
    { "id": "dino",       "emoji": "🦖", "title": "The Case of the Dinosaur on the Wall", "blurb": "Someone drew a T-Rex on the hallway wall. In permanent marker. Honestly, it's pretty good." },
    { "id": "remote",     "emoji": "📺", "title": "The Case of the Missing Remote",       "blurb": "The TV remote has vanished. The family has been watching the same channel for three hours." },
    { "id": "toot",       "emoji": "💨", "title": "The Case of the Mystery Toot",         "blurb": "Somebody let one rip in the car with the windows up. Nobody is admitting anything." },
    { "id": "toothbrush", "emoji": "🪥", "title": "The Case of the Toothbrush in the Toilet", "blurb": "Dad's toothbrush was found floating in the toilet. Dad is not happy." },
    { "id": "glitter",    "emoji": "✨", "title": "The Case of the Glitter Explosion",    "blurb": "A tub of glitter exploded in the living room. We'll be finding glitter until Christmas. Next Christmas." },
    { "id": "dogpants",   "emoji": "🐶", "title": "The Case of the Dog in Underpants",    "blurb": "The dog is wearing underpants. Somebody dressed him. He seems fine with it." },
    { "id": "freezersock","emoji": "🧦", "title": "The Case of the Sock in the Freezer",  "blurb": "A single sock was found in the freezer next to the peas. It is very cold now." },
    { "id": "cereal",     "emoji": "🥣", "title": "The Case of the Empty Cereal Box",     "blurb": "Someone finished the cereal and put the EMPTY box back in the cupboard. A crime against breakfast." },
    { "id": "mummy",      "emoji": "🧻", "title": "The Case of the Toilet Paper Mummy",   "blurb": "An entire roll of toilet paper was wrapped around the hallway. It looks like a mummy lives here." },
    { "id": "thermostat", "emoji": "🌡️", "title": "The Case of the Thermostat Bandit",   "blurb": "Somebody cranked the heat all the way up. The house is a sauna. The goldfish is sweating." },
    { "id": "wifi",       "emoji": "📶", "title": "The Case of the Unplugged Wi-Fi",      "blurb": "The Wi-Fi was unplugged during the season finale. Someone in this house did this on purpose." },
    { "id": "peanut",     "emoji": "🥜", "title": "The Case of the Peanut Butter Handprints", "blurb": "Peanut butter handprints. On the wall. On the door. On the cat." },
    { "id": "doorbell",   "emoji": "🔔", "title": "The Case of the Doorbell Ditcher",     "blurb": "Someone rang the doorbell six times and ran away. From INSIDE the house." },
    { "id": "leftshoes",  "emoji": "👟", "title": "The Case of the Missing Left Shoes",   "blurb": "Every left shoe in the house is gone. Only the right shoes remain. Why?" },
    { "id": "ketchup",    "emoji": "🍅", "title": "The Case of the Ketchup on the Ceiling","blurb": "There is ketchup on the ceiling. Nobody knows how. Nobody knows why." },
    { "id": "mustache",   "emoji": "🐱", "title": "The Case of the Cat's Mustache",       "blurb": "The cat woke up with a marker mustache. The cat is furious and, honestly, kind of dashing." },
    { "id": "blocks",     "emoji": "🧱", "title": "The Case of the Bathtub of Blocks",    "blurb": "The bathtub is full of building blocks. Stepping in it would be extremely painful." },
    { "id": "milk",       "emoji": "🥛", "title": "The Case of the One Drop of Milk",     "blurb": "The milk carton was put back with exactly one drop left. One. Drop." },
    { "id": "vase",       "emoji": "🏺", "title": "The Case of Grandma's Vase",           "blurb": "Grandma's favorite vase is in pieces. Grandma is visiting tomorrow." },
    { "id": "pizza",      "emoji": "🍕", "title": "The Case of the Picked-Off Pizza",     "blurb": "Every single topping was picked off the pizza. The cheese remains, sad and alone." },
    { "id": "bubbles",    "emoji": "🫧", "title": "The Case of the Bubble Bath Volcano",  "blurb": "Someone poured the whole bottle of bubble bath in the tub. The bathroom is now a foam mountain." },
    { "id": "homework",   "emoji": "📚", "title": "The Case of the Homework Eater",       "blurb": "The homework was found with bite marks. Real bite marks. Human sized." },
    { "id": "slime",      "emoji": "🟢", "title": "The Case of the Slime in the Sink",    "blurb": "The kitchen sink is full of green slime. It is bubbling." },
    { "id": "fridge",     "emoji": "🧊", "title": "The Case of the Remote in the Fridge", "blurb": "The remote was found in the fridge, next to the butter. It's very cold." },
    { "id": "spider",     "emoji": "🕷️", "title": "The Case of the Fake Spider",         "blurb": "A giant fake spider was placed in Mom's shoe. The scream was heard three streets away." },
    { "id": "pancake",    "emoji": "🥞", "title": "The Case of the Pancake on the Fan",   "blurb": "A pancake is stuck to the ceiling fan. It spins around. Round and round and round." },
    { "id": "doorknobs",  "emoji": "🚪", "title": "The Case of the Sticky Doorknobs",     "blurb": "Every doorknob in the house is sticky. Every. Single. One." },
    { "id": "cookiejar",  "emoji": "🍪", "title": "The Case of the Cookie Jar Crumbs",    "blurb": "The cookie jar contains nothing but crumbs and a tiny note that says ha ha." },
    { "id": "gnome",      "emoji": "🧙", "title": "The Case of the Gnome-napping",        "blurb": "The garden gnome is missing. A ransom note demands three cookies." },
    { "id": "alarm",      "emoji": "⏰", "title": "The Case of the Four A.M. Alarm",      "blurb": "Someone set every alarm in the house for four in the morning. Nobody has slept." },
    { "id": "potato",     "emoji": "🥔", "title": "The Case of the Photo Swap",           "blurb": "The family photo on the fridge was replaced with a picture of a potato." },
    { "id": "teddy",      "emoji": "🧸", "title": "The Case of the Teddy Bear Lineup",    "blurb": "All the teddy bears were lined up on the stairs, wearing tiny sunglasses. Somebody had a lot of free time." },
    { "id": "bluebath",   "emoji": "🎨", "title": "The Case of the Blue Bathwater",       "blurb": "The bath water turned bright blue. So did the dog." },
    { "id": "balloons",   "emoji": "🎈", "title": "The Case of the Balloon Hallway",      "blurb": "The hallway is packed floor to ceiling with balloons. Nobody can get to the bathroom." },
    { "id": "couch",      "emoji": "🍫", "title": "The Case of the Chocolate Fingerprint","blurb": "A chocolate fingerprint was found on the brand new white couch. A big one." },
    { "id": "savefile",   "emoji": "🎮", "title": "The Case of the Deleted Save File",    "blurb": "Somebody deleted the game save file. Ninety hours of progress. Gone." },
    { "id": "salt",       "emoji": "🧂", "title": "The Case of the Salty Sugar Bowl",     "blurb": "The sugar bowl was filled with salt. Grandpa's coffee has never been so terrible." },
    { "id": "wrap",       "emoji": "🚽", "title": "The Case of the Plastic-Wrapped Toilet","blurb": "The toilet seat was wrapped in plastic wrap. Someone found out the hard way." },
    { "id": "karaoke",    "emoji": "🎤", "title": "The Case of the Midnight Karaoke",     "blurb": "Someone sang karaoke at full volume at midnight. The neighbors have written a letter." }
  ],
  "finalWords": [
    "It wasn't me. I was busy being adorable.",
    "I would never. Well, hardly ever.",
    "I plead the fifth. Also the sixth.",
    "Look into my eyes. These are innocent eyes.",
    "Why would I do that? Okay, don't answer that.",
    "I have an alibi and a lawyer. The lawyer is my teddy bear.",
    "You can't prove anything. Right? Right?!",
    "I'm too cute to be a criminal.",
    "The real criminal is still out there. Probably.",
    "I was framed! By whoever is looking at me right now.",
    "I demand a snack break before the vote.",
    "I saw nothing. I heard nothing. I ate nothing.",
    "Whoever smelt it, dealt it. That's the law.",
    "I was asleep. With my eyes open. It's a talent.",
    "Vote for me and I'll... wait. Don't vote for me.",
    "Honestly? I'm just here for the snacks.",
    "The dog did it. Trust me.",
    "Do I LOOK like a criminal? Don't answer that.",
    "I'm not guilty. I'm just extremely suspicious.",
    "I've never even heard of a cupcake.",
    "My alibi is airtight. Like a balloon. Please don't pop it.",
    "Objection! I don't know what that means, but objection!",
    "I have a very good reason and I'll think of it later.",
    "If I did it, would I be this calm? I'm not calm."
  ],
  "twists": [
    { "id": "accomplice", "emoji": "🤝", "name": "Double Trouble",     "desc": "The culprit has a secret accomplice.", "minPlayers": 4 },
    { "id": "chief",      "emoji": "🎖️", "name": "Detective in Chief", "desc": "One detective gets two witness peeks and breaks ties.", "minPlayers": 3 },
    { "id": "blackout",   "emoji": "🔦", "name": "Blackout",           "desc": "Clues show for only five seconds. Pay attention!", "minPlayers": 3 },
    { "id": "speed",      "emoji": "⚡", "name": "Speed Case",         "desc": "Every timer is cut in half. Think fast!", "minPlayers": 3 },
    { "id": "serum",      "emoji": "🧪", "name": "Truth Serum",        "desc": "One witness statement is stamped VERIFIED by the Inspector.", "minPlayers": 4 }
  ],
  "stickers": {
    "sharp":   { "emoji": "🎯", "name": "Sharp Eye",        "desc": "First to vote for the culprit" },
    "poker":   { "emoji": "🎭", "name": "Poker Face",       "desc": "Escaped as the culprit" },
    "framed":  { "emoji": "🫣", "name": "Framed",           "desc": "Innocent, but got the most votes" },
    "witness": { "emoji": "🗣️", "name": "Key Witness",      "desc": "Your peek exposed the culprit" },
    "partner": { "emoji": "🤝", "name": "Partner in Crime", "desc": "Accomplice on a clean getaway" },
    "slow":    { "emoji": "🐢", "name": "Slowpoke",         "desc": "Last to vote" },
    "drama":   { "emoji": "🎪", "name": "Drama Star",       "desc": "Most reactions in a case" },
    "liar":    { "emoji": "🤥", "name": "Big Fibber",       "desc": "Framed someone and got away with it" },
    "nose":    { "emoji": "👃", "name": "Nose for Trouble", "desc": "Voted for the culprit three cases in a row" }
  },
  "ranks": [
    { "min": 0,   "name": "Rookie",               "emoji": "🥚" },
    { "min": 12,  "name": "Junior Sleuth",        "emoji": "🔍" },
    { "min": 30,  "name": "Gumshoe",              "emoji": "👟" },
    { "min": 60,  "name": "Inspector",            "emoji": "🎩" },
    { "min": 110, "name": "Super Sleuth",         "emoji": "🕵️" },
    { "min": 180, "name": "Legendary Detective",  "emoji": "👑" }
  ],
  "lines": {
    "lobby": ["Welcome, detectives. Scan the code on the screen to join. Somebody in this room is about to be in big trouble."],
    "lobbyJoin": ["A new suspect has entered the room.", "Ooh, another one. Interesting.", "Welcome. Try not to look guilty."],
    "gameStart": ["Everyone's here? Wonderful. Let's begin. Nobody leaves until we find the truth."],
    "caseIntro": ["A crime has been committed. Listen carefully.", "Oh no. Not again. Here's what happened.", "Attention, everyone. We have a situation."],
    "roles": ["Now check your phones. Somebody in this room is guilty. Don't look at me like that, I'm just the cat."],
    "rolesWait": ["Take your time. Not too much time."],
    "lineup": ["Let's hear those alibis. Where was everyone, what were they wearing, and what were they snacking on?"],
    "lineupAfter": ["Hmm. Somebody is lying. I can smell it. And I have an excellent nose."],
    "clue1": ["Time for our first clue."],
    "clue2": ["Clue number two."],
    "clue3": ["And now, the final clue."],
    "clueMatch": ["Ooh. Somebody's alibi just got a lot more interesting.", "Well, well, well. Look who that matches.", "Interesting. Very interesting."],
    "clueNoMatch": ["Nobody said that. So somebody isn't telling the truth.", "That matches no one. Which means someone is lying."],
    "witness": ["Witnesses, step forward. Check your phones and tell us what you saw."],
    "witnessBoard": ["Let's see what the witnesses had to say."],
    "contradiction": ["That's not what they told us!", "Ooh. Somebody's story doesn't add up."],
    "finalWords": ["Any final words before the vote? Pick your best defense."],
    "vote": ["Time to vote. Point your finger, and tap that face."],
    "voteHurry": ["Ten seconds. Trust your gut."],
    "votesIn": ["The votes are in."],
    "reveal": ["The culprit was..."],
    "caught": ["Caught red-handed! Justice is served.", "Gotcha! The detectives win this one.", "Busted! I knew it all along. I just didn't say anything."],
    "escaped": ["They got away with it! Outrageous!", "Unbelievable. The culprit walks free.", "Wrong! The real culprit is laughing right now."],
    "accompliceReveal": ["And they had help. The accomplice was..."],
    "tie": ["A tie! And when it's a tie, the culprit walks."],
    "chiefTie": ["A tie! The Detective in Chief decides."],
    "scores": ["Here's the scoreboard."],
    "nextCase": ["Ready for another case? Of course you are."],
    "gameEnd": ["Case closed. Well done, detectives. Here are tonight's results."],
    "teaser": ["Next time, on Family Whodunit..."],
    "twist": ["This case has a twist!"],
    "junior": ["This case has two sneaky people in it. Watch out."],
    "skip": ["Moving on."],
    "itWas": ["It was"],
    "unlock": ["A new suspect has been unlocked!"]
  },
  "reactions": ["😱", "😂", "🤔", "🙄"]
};
